-- Add test data with actual risk levels for testing risk charts and tables
-- This should be run after loading the main seed data

-- Insert messages with different risk levels
INSERT INTO "public"."enriched_messages" ("id", "created_at", "updated_at", "user_id", "message_id", "message_provider_id", "overall_risk_level", "overall_risk_score", "risk_categories", "risk_summary", "detected_issues", "user_whitelist", "processing_time_ms", "model_used") VALUES
	-- High risk - PII detected
	(1001, '2025-10-15 10:30:00+00', '2025-11-24 21:01:38.720711+00', 'eff2a1fd-210c-4b44-9a6f-81af6534c3c8', NULL, 'test-msg-001', 'high', 65.00, '{"pii": {"level": "high", "score": 70, "details": "Personal email and phone number detected", "detected": true}, "security": {"level": "none", "score": 10, "details": "No security credentials detected", "detected": false}, "compliance": {"level": "medium", "score": 60, "details": "GDPR compliance concern with personal data", "detected": true}, "confidential": {"level": "none", "score": 10, "details": "No confidential business data detected", "detected": false}, "data_leakage": {"level": "none", "score": 10, "details": "No data leakage detected", "detected": false}, "misinformation": {"level": "none", "score": 10, "details": "No misinformation detected", "detected": false}}', '{"summary": "PII and compliance risks detected"}', '["Personal email address", "Phone number"]', false, 250, 'gpt-4'),

	-- Critical risk - Security credentials
	(1002, '2025-10-16 14:22:00+00', '2025-11-24 21:01:38.720711+00', 'eff2a1fd-210c-4b44-9a6f-81af6534c3c8', NULL, 'test-msg-002', 'critical', 85.00, '{"pii": {"level": "none", "score": 10, "details": "No PII detected", "detected": false}, "security": {"level": "critical", "score": 90, "details": "API key and password detected in message", "detected": true}, "compliance": {"level": "high", "score": 70, "details": "Security policy violation", "detected": true}, "confidential": {"level": "medium", "score": 60, "details": "Internal system details exposed", "detected": true}, "data_leakage": {"level": "high", "score": 75, "details": "Internal configuration details leaked", "detected": true}, "misinformation": {"level": "none", "score": 10, "details": "No misinformation detected", "detected": false}}', '{"summary": "Critical security risks with credentials exposure"}', '["API key", "Password", "Internal config"]', false, 280, 'gpt-4'),

	-- Medium risk - Confidential data
	(1003, '2025-10-18 09:15:00+00', '2025-11-24 21:01:38.720711+00', 'eff2a1fd-210c-4b44-9a6f-81af6534c3c8', NULL, 'test-msg-003', 'medium', 55.00, '{"pii": {"level": "low", "score": 30, "details": "Name mentioned in context", "detected": true}, "security": {"level": "none", "score": 10, "details": "No security issues", "detected": false}, "compliance": {"level": "none", "score": 10, "details": "No compliance issues", "detected": false}, "confidential": {"level": "medium", "score": 60, "details": "Business strategy information shared", "detected": true}, "data_leakage": {"level": "medium", "score": 55, "details": "Internal project details mentioned", "detected": true}, "misinformation": {"level": "none", "score": 10, "details": "No misinformation", "detected": false}}', '{"summary": "Medium risk with confidential business data"}', '["Business strategy", "Project details"]', false, 220, 'claude-3'),

	-- Low risk - Minor PII
	(1004, '2025-10-20 16:45:00+00', '2025-11-24 21:01:38.720711+00', 'eff2a1fd-210c-4b44-9a6f-81af6534c3c8', NULL, 'test-msg-004', 'low', 35.00, '{"pii": {"level": "low", "score": 40, "details": "First name mentioned", "detected": true}, "security": {"level": "none", "score": 10, "details": "No security issues", "detected": false}, "compliance": {"level": "none", "score": 10, "details": "No compliance issues", "detected": false}, "confidential": {"level": "none", "score": 10, "details": "No confidential data", "detected": false}, "data_leakage": {"level": "low", "score": 30, "details": "Minor internal reference", "detected": true}, "misinformation": {"level": "none", "score": 10, "details": "No misinformation", "detected": false}}', '{"summary": "Low risk with minor PII"}', '["First name"]', false, 180, 'gpt-4'),

	-- High risk - Multiple categories
	(1005, '2025-10-22 11:20:00+00', '2025-11-24 21:01:38.720711+00', 'eff2a1fd-210c-4b44-9a6f-81af6534c3c8', NULL, 'test-msg-005', 'high', 70.00, '{"pii": {"level": "high", "score": 75, "details": "Email, phone, and address detected", "detected": true}, "security": {"level": "medium", "score": 50, "details": "Partial credentials visible", "detected": true}, "compliance": {"level": "high", "score": 70, "details": "HIPAA violation potential", "detected": true}, "confidential": {"level": "medium", "score": 55, "details": "Customer data shared", "detected": true}, "data_leakage": {"level": "none", "score": 10, "details": "No data leakage", "detected": false}, "misinformation": {"level": "none", "score": 10, "details": "No misinformation", "detected": false}}', '{"summary": "Multiple high-risk categories detected"}', '["Email", "Phone", "Address", "Customer data"]', false, 310, 'gpt-4'),

	-- Critical risk - Data leakage
	(1006, '2025-10-25 13:30:00+00', '2025-11-24 21:01:38.720711+00', 'eff2a1fd-210c-4b44-9a6f-81af6534c3c8', NULL, 'test-msg-006', 'critical', 90.00, '{"pii": {"level": "none", "score": 10, "details": "No PII", "detected": false}, "security": {"level": "critical", "score": 95, "details": "Database credentials and connection strings exposed", "detected": true}, "compliance": {"level": "critical", "score": 90, "details": "Critical security policy violation", "detected": true}, "confidential": {"level": "critical", "score": 85, "details": "Proprietary source code shared", "detected": true}, "data_leakage": {"level": "critical", "score": 95, "details": "Database schema and credentials leaked", "detected": true}, "misinformation": {"level": "none", "score": 10, "details": "No misinformation", "detected": false}}', '{"summary": "Critical data leakage with database credentials"}', '["DB credentials", "Connection string", "Source code"]', false, 350, 'claude-3');

-- Update the sequence to account for new IDs
SELECT pg_catalog.setval('"public"."enriched_messages_id_seq"', 1006, true);
